default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: evently_dev

test:
  <<: *default
  database: evently_test

production:
  <<: *default
  database: evently_prod
